Feature: Add Edit on GitHub to HTML layout and GitHub issue templates

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -46,11 +46,18 @@ check_format:
     - git clone -b new_check_format $SCRIPTS_REPO
     - echo "$CHANGED_FILES"
     - |
-      output=$(bash check_docs_modules/check_rst_format.sh $CHANGED_FILES)
-      echo "$output"
-      # Check if the output of the script contains any syntax errors
-      if echo "$output" | grep -q "Syntax check found"; then
-        exit 1  # Fail the pipeline if syntax errors are found
+      # Filter only .rst files
+      RST_FILES=$(echo "$CHANGED_FILES" | tr ' ' '\n' | grep '\.rst$' || true)
+
+      if [ -n "$RST_FILES" ]; then
+        output=$(bash check_docs_modules/check_rst_format.sh $RST_FILES)
+        echo "$output"
+        # Check if the output of the script contains any syntax errors
+        if echo "$output" | grep -q "Syntax check found"; then
+          exit 1  # Fail the pipeline if syntax errors are found
+        fi
+      else
+        echo "No .rst files to check."
       fi
 
 .build_template:
